In [2]:
import numpy as np

In [3]:
deck_of_cards=np.ones((13, 4), dtype=bool)

In [167]:
deck_of_cards
del deck_of_cards
deck_of_cards

NameError: name 'deck_of_cards' is not defined

In [8]:
# draw a card from the deck

np.random.rand(1)

array([0.75468868])

In [9]:
a =['A','K','Q','J']

In [10]:
type(a)

list

In [12]:
b =('A','K','Q','J')

In [14]:
type(b)

tuple

In [323]:


type(value_list)
print(value_list)

[2, 3, 4, 5, 6, 7, 8, 9, 10, 'Jack', 'Queen', 'King', 'Ace']


In [240]:
deck_index=0;
deck_length,var_num = len(value_list)*len(suit_list),2
new_var = [ [None]*var_num for i in range(w) ]
#new_var=[None]*len(value_list)*len(suit_list)
for suit_index in range(len(suit_list)):
    for value_index in range(len(value_list)):
    
        new_var[deck_index][0] = suit_list[suit_index]
        new_var[deck_index][1] = value_list[value_index]
        deck_index +=1
     

len(new_var)

52

In [404]:
#CREATE deck of cards
import math

suit_list = ('Spades','Clubs','Diamonds','Hearts')
value_list = list(range(2,11)) +['Jack','Queen','King','Ace']

#deck_of_cards=np.ones((13, 4), dtype=bool)
array_of_cards = np.linspace(0,51,51,dtype = int)
deck_size = 52;




In [395]:
#shuffle deck
np.random.shuffle(array_of_cards)

#draw first card after the deck has been shuffles
current_card = array_of_cards[0]

#remove drawn card from deck
array_of_cards=array_of_cards[1:]

#determine suit and value of drawn card
value_id  = current_card % (len(value_list))
suit_id  = math.floor(current_card/len(value_list))



print('current card is the  = ' + str(value_list[value_id]) + ' of ' + suit_list[suit_id])
print('There are ' + str(len(array_of_cards)) + ' cards remaining')

current card is the  = 5 of Hearts
There are 49 cards remaining


In [703]:
# create deck
#deck_of_cards=np.ones((13, 4), dtype=bool)
array_of_cards = np.linspace(0,51,51,dtype = int)
deck_size = 52;

#deal hands to very player
#shuffle deck
np.random.shuffle(array_of_cards)


number_of_players  = 3
cards_per_hand = 3
hands = np.zeros((number_of_players,cards_per_hand,3),dtype=int)
hands_named = [ [None]*cards_per_hand for i in range(number_of_players) ]
for player_index in range(number_of_players):
    for card_index in range(cards_per_hand):
        #draw first card after the deck has been shuffles
        current_card = array_of_cards[0]

        #remove drawn card from deck
        array_of_cards=array_of_cards[1:]
        #deal card
        
        value_id  = current_card % (len(value_list))
        suit_id  = math.floor(current_card/len(value_list))
        hands[player_index][card_index] = [current_card, value_id, suit_id]
        hands_named[player_index][card_index] = [value_list[value_id], suit_list[suit_id]]
    print(hands_named[player_index])


[[4, 'Diamonds'], [9, 'Clubs'], [9, 'Spades']]
[[7, 'Clubs'], [6, 'Diamonds'], [7, 'Spades']]
[['Queen', 'Clubs'], [10, 'Diamonds'], ['King', 'Diamonds']]


In [799]:
#determine the probability of having a winning hand, prior to seeing the other players' hands or
#the shared cards
pair_logical = np.zeros((number_of_players, cards_per_hand), dtype=bool)
# does the current hand contain a pair
for player_index in range(number_of_players):
    hand_values = hands[player_index,:,1]
  
    unique_values, i = np.unique(hand_values,return_index=True)

    print('player ' + str(player_index) + ' = ' + str(hands_named[player_index]))
    for index_1 in range(len(unique_values)):

            if sum(hand_values == unique_values[index_1])>1:
                print('player number ' + str(player_index) + ' has a pair of ' + str(value_list[unique_values[index_1]]))
       
                hand_values = hand_values[hand_values != unique_values[index_1]]
             
               
                pair_logical[player_index,hands[player_index,:,1] == unique_values[index_1]]=True
    max_not_pair = np.max(hands[player_index,~pair_logical[player_index,:],1])
    
    print('player ' + str(player_index) + ' has a top unpaired card of ' + str(value_list[max_not_pair]) )
    
    
        

                
                
        
    
            
                    

player 0 = [[4, 'Diamonds'], [9, 'Clubs'], [9, 'Spades']]
player number 0 has a pair of 9
player 0 has a top unpaired card of 4
player 1 = [[7, 'Clubs'], [6, 'Diamonds'], [7, 'Spades']]
player number 1 has a pair of 7
player 1 has a top unpaired card of 6
player 2 = [['Queen', 'Clubs'], [10, 'Diamonds'], ['King', 'Diamonds']]
player 2 has a top unpaired card of King


In [901]:
from itertools import compress
list_a = ['a','b','temp',2]
fil = [True,True,False,True]
print(list(compress(list_a, fil)))


['a', 'b', 2]


In [936]:
list_a = [1, 2, 4, 6]
filter_vec = [True, False, True, False]
#iltered_list = [i for indx,i in enumerate(list_a) if filter_vec[indx]]
filtered_list = [ oddly for indx,oddly in enumerate(list_a) if filter_vec[indx]]
print(filtered_list)

        
        


[1, 4]


In [898]:

list_a = ['a','b','temp',2]

list(compress(list_a, fil))


list_a = ['a','b','3']
array_b = np.array([1,2,3])
array_c = np.repeat(np.arange(8),3,axis=1)

print(array_b[[0,2]])
print(array_c)
print(np.reshape(array_c,(8,1)))

AxisError: axis 1 is out of bounds for array of dimension 1

In [894]:
a =np.mgrid[0:5,0:5]
print(a.shape)
print(a)
b = np.zeros([2,3])
print(b[0,0])

x = np.array([1,2,3])
a = np.arange(3,dtype=int)
print(type(a))
a = np.reshape(a,(1,3))
a = np.repeat(a,3,axis=0)
#print(a * x)
#print(x.shape)
print(a.shape)

print(a[:,[0,1]])

(2, 5, 5)
[[[0 0 0 0 0]
  [1 1 1 1 1]
  [2 2 2 2 2]
  [3 3 3 3 3]
  [4 4 4 4 4]]

 [[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]]
0.0
<class 'numpy.ndarray'>
(3, 3)
[[0 1]
 [0 1]
 [0 1]]


In [ ]:
### determine if either player has any pairs
pairs_found = np.zeros(number_of_players,dtype=bool)
for player_index in range(number_of_players):
    unique_values, card_index = np.unique(hands[player_index,:,1],return_index=True)
    if len(unique_values)!=hands.shape[2]:
        pairs_found[player_index] = True
    Z

In [648]:
hands.shape

(10, 2, 3)

In [488]:
card_index

array([3, 4, 0, 1], dtype=int64)

In [712]:
a = True(1,2)




TypeError: 'bool' object is not callable

In [459]:
hands

array([[[1, 2],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

In [297]:
a=4%3
a

1

In [55]:
suit_index

1

In [85]:
value_list[0][0]

2.0

In [86]:
a = np.linspace(2,10,9)

In [87]:
a

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [89]:
b =list(a)

In [90]:
type(b)

list

In [118]:
value_list = list(np.linspace(2,10,9))

In [103]:
value_list[0]

2.0

In [116]:
face_cards = ['Jack','Queen','King','Ace']
value_list.append(list(face_cards))

In [119]:
value_list

[2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]

In [114]:
list(face_cards)

['Jack', 'Queen', 'King', 'Ace']

In [131]:
# Your original list of numpy arrays ...
b = [np.array([5, 7]), np.array([5, 5])]
# ... can be converted to list of lists
c = [list(x) for x in b]

In [133]:
c[0]

[5, 7]

In [134]:
a = 'Hello' + 'World'

In [135]:
a

'HelloWorld'

In [139]:
a = ['King']

In [140]:
b = [1]

In [141]:
a+b

['King', 1]

In [189]:
x = [[2,6],[6,2],[8,2],[5,12]]

In [190]:
shape(x)

NameError: name 'shape' is not defined

In [191]:
x.shape

AttributeError: 'list' object has no attribute 'shape'