In [2]:
import numpy as np
import math

In [9]:
#CREATE deck of cards


suit_list = ('Spades','Clubs','Diamonds','Hearts')
value_list = list(range(2,11)) +['Jack','Queen','King','Ace']






In [29]:
# create deck
#deck_of_cards=np.ones((13, 4), dtype=bool)
array_of_cards = np.linspace(0,51,51,dtype = int)
deck_size = 52;

#deal hands to very player
#shuffle deck
np.random.shuffle(array_of_cards)


number_of_players  = 3
cards_per_hand = 2
hands = np.zeros((number_of_players,cards_per_hand,3),dtype=int)
hands_named = [ [None]*cards_per_hand for i in range(number_of_players) ]
for player_index in range(number_of_players):
    for card_index in range(cards_per_hand):
        #draw first card after the deck has been shuffles
        current_card = array_of_cards[0]

        #remove drawn card from deck
        array_of_cards=array_of_cards[1:]
        #deal card
        
        value_id  = current_card % (len(value_list))
        suit_id  = math.floor(current_card/len(value_list))
        hands[player_index][card_index] = [current_card, value_id, suit_id]
        hands_named[player_index][card_index] = [value_list[value_id], suit_list[suit_id]]
    print(hands_named[player_index])


[['Jack', 'Diamonds'], [6, 'Clubs']]
[[4, 'Diamonds'], ['Queen', 'Spades']]
[[3, 'Hearts'], [8, 'Hearts']]


In [163]:



#determine the probability of having a winning hand, prior to seeing the other players' hands or
#the shared cards
pair_logical = np.zeros((number_of_players, cards_per_hand), dtype=bool)
# does the current hand contain a pair
for player_index in range(number_of_players):
    hand_values = hands[player_index,:,1]
  
    unique_values, i = np.unique(hand_values,return_index=True)

    print('player ' + str(player_index) + ' = ' + str(hands_named[player_index]))
    for index_1 in range(len(unique_values)):

            if sum(hand_values == unique_values[index_1])>1:
                print('player number ' + str(player_index) + ' has a pair of ' + str(value_list[unique_values[index_1]]))
       
                hand_values = hand_values[hand_values != unique_values[index_1]]
             
               
                pair_logical[player_index,hands[player_index,:,1] == unique_values[index_1]]=True
    max_not_pair = np.max(hands[player_index,~pair_logical[player_index,:],1])
    
    
    
    if sum(pair_logical[player_index,:]) == 0:
        
        possible_community = math.factorial(50)/(math.factorial(50-5)* math.factorial(5)) 
        possible_matches = math.factorial(3)/(math.factorial(3-1)* math.factorial(1)) *  \
        math.factorial(47)/(math.factorial(47-4)* math.factorial(4))
        print(str(100* possible_matches/possible_community) + ' odds of a  ' + str(value_list[max_not_pair]))
        

                





    
            
                    

player 0 = [['Jack', 'Diamonds'], [6, 'Clubs']]
25.255102040816325 odds of a  Jack
player 1 = [[4, 'Diamonds'], ['Queen', 'Spades']]
25.255102040816325 odds of a  Queen
player 2 = [[3, 'Hearts'], [8, 'Hearts']]
25.255102040816325 odds of a  8


In [87]:
num_players = 3 # not including self
#odds of a better high card in any other player's hole cards

#total number of possible card combos in any single opponent's hands

total_combos =math.factorial(50)/(math.factorial(50-2)*math.factorial(2))

#total number of possible card combos in  n opponents' hands doesn't change, same number of 
#possible combos, the odds of any given combo increases

#better than a 9
rank = 13 - 11
better_cards = rank*4
worse_cards = 52 - better_cards
better_combos = math.factorial(better_cards)/(math.factorial(better_cards-1)*math.factorial(1)) * \
math.factorial(49)/(math.factorial(49-1)*math.factorial(1))
better_combos /= math.factorial(2)
percent_better = better_combos/total_combos
print(percent_better)

print(str(1 - (1-percent_better)**num_players) + ' of hands at least 1 player has a better high card')


0.16
0.4072960000000001 of hands at least 1 player has a better high card


In [79]:
.08*.08*.08 + 3*(.08*.92*.92) + 3*(.08*.08*.92)

0.22131200000000006

In [88]:

#odds of getting a pair (for one of your pcokert cards ) in the community cards

#50 unknown cards and 3 possible matches, 5 community cards

#possible combinations of community cards
possible_community = math.factorial(50)/(math.factorial(50-5)* math.factorial(5)) 


possible_matches = math.factorial(3)/(math.factorial(3-1)* math.factorial(1)) *  \
math.factorial(47)/(math.factorial(47-4)* math.factorial(4))


print('There is a ' + str(possible_matches/possible_community) + ' odds of getting a pair with pocket card 1')

possible_matches = math.factorial(6)/(math.factorial(6-1)* math.factorial(1)) *  \
math.factorial(44)/(math.factorial(44-4)* math.factorial(4))
print('There is a ' + str(possible_matches/possible_community) + ' odds of getting a pair with either pocket card')

possible_triples = (math.factorial(3)/(math.factorial(3-1)* math.factorial(1))) *  \
(math.factorial(3)/(math.factorial(3-1)* math.factorial(1))) *  \
math.factorial(44)/(math.factorial(44-3)* math.factorial(3))

print('There is a ' + str(possible_triples/possible_community) + ' odds of getting a three of a kind with pocket card 1')

#if you have suited pocket cards, what are the odds of getting a flush
# there are 11 other cards to match your suit
possible_flushes = math.factorial(11)/(math.factorial(11-3)* math.factorial(3)) *  \
math.factorial(39)/(math.factorial(39-2)* math.factorial(2))
print('There is a ' + str(possible_flushes/possible_community) + ' odds of getting a flush when you have suited pocket cards')


#if the first flop card is suited
possible_community = math.factorial(49)/(math.factorial(49-4)* math.factorial(4)) 
possible_flushes = math.factorial(10)/(math.factorial(10-2)* math.factorial(2)) *  \
math.factorial(39)/(math.factorial(39-2)* math.factorial(2))
print('There is a ' + str(possible_flushes/possible_community) + ' odds of getting a flush after flop 1')

#if the first flop card is not  suited
possible_community = math.factorial(49)/(math.factorial(49-4)* math.factorial(4)) 
possible_flushes = math.factorial(11)/(math.factorial(11-3)* math.factorial(3)) *  \
math.factorial(38)/(math.factorial(38-1)* math.factorial(1))
print('There is a ' + str(possible_flushes/possible_community) + ' odds of getting a flush after flop 1 not suited')

#if the second flop card is suited
possible_community = math.factorial(48)/(math.factorial(48-3)* math.factorial(3)) 
possible_flushes = math.factorial(9)/(math.factorial(9-1)* math.factorial(1)) *  \
math.factorial(39)/(math.factorial(39-2)* math.factorial(2))
print('There is a ' + str(possible_flushes/possible_community) + ' odds of getting a flush after flop 2')

#if the second flop card is not suited
possible_community = math.factorial(48)/(math.factorial(48-3)* math.factorial(3)) 
possible_flushes = math.factorial(10)/(math.factorial(10-0)* math.factorial(3)) *  \
math.factorial(37)/(math.factorial(37-0)* math.factorial(0))
print('There is a ' + str(possible_flushes/possible_community) + ' odds of getting a flush after flop 2 not suited')


print('if the third flop card is suited  you have a flush')

There is a 0.25255102040816324 odds of getting a pair with pocket card 1
There is a 0.3844257962204308 odds of getting a pair with either pocket card
There is a 0.056257433593233784 odds of getting a three of a kind with pocket card 1
There is a 0.05770592233192999 odds of getting a flush when you have suited pocket cars
There is a 0.1573797881779909 odds of getting a flush after flop 1
There is a 0.02959278068304102 odds of getting a flush after flop 1 not suited
There is a 0.3855804810360777 odds of getting a flush after flop 2
There is a 9.63613937711995e-06 odds of getting a flush after flop 2 not suited
if the third flop card is suited  you have a flush


In [82]:
# odds of getting a straight

1.7959947327164457e+57

In [146]:
# odds of getting a straight in 5 card draw
possible_hands = math.factorial(52)/(math.factorial(52-5)* math.factorial(5)) 
#10 differnt anchor values (e.g., [2,3,4,5,6] or [4,5,6,7,8])
possible_anchor = math.factorial(10)/(math.factorial(10-1)* math.factorial(1)) 
#4 possible suits
possible_anchor *=(math.factorial(4)/(math.factorial(4-1)* math.factorial(1)))**5
#1 combo of strain cards given your anchor card
#exclude flushes. For each straight, there is 1 case where it is actually a flush
possible_anchor -= math.factorial(10)/(math.factorial(10-1)* math.factorial(1))  * \
(math.factorial(4)/(math.factorial(4-1)* math.factorial(1)))

print(100*possible_anchor/possible_hands)


0.3924646781789639


In [152]:
# odds of getting a straight in the community, given that your two pocket cards can be used as a 2 card anchor
possible_hands = math.factorial(52)/(math.factorial(52-7)* math.factorial(7))
possible_community = math.factorial(50)/(math.factorial(50-5)* math.factorial(5)) 

#there are 5 consequitve values in a straight, you already have two, so you need three more
possible_completion = math.factorial(3)/(math.factorial(3-1)* math.factorial(3)) 
#4 possible suits
possible_completion *=(math.factorial(4)/(math.factorial(4-1)* math.factorial(1)))**3

#all the way the remaning 2 cards fill out the hand
possible_completion *= math.factorial(47)/(math.factorial(47-2)* math.factorial(2)) 

#exclude flushes. For each straight, there is 1 case where it is actually a flush
#possible_completion -= math.factorial(10)/(math.factorial(10-1)* math.factorial(1))  * \
#(math.factorial(4)/(math.factorial(4-1)* math.factorial(1)))
#1 combo of strain cards given your anchor card


print(possible_completion/possible_community)

print(math.factorial(47)/(math.factorial(47-2)* math.factorial(2)))

0.0163265306122449
1081.0


In [137]:
#odds of getting pocket cards that can anchor a straight
possible_hands = math.factorial(52)/(math.factorial(52-2)* math.factorial(2)) 
possible_anchor = math.factorial(9)/(math.factorial(9-1)* math.factorial(1))  * \
((math.factorial(4)/(math.factorial(4-1)* math.factorial(1)))**2)

#possible_anchor -= math.factorial(10)/(math.factorial(10-1)* math.factorial(1))

#print(possible_hands)
#print(possible_anchor)
possible_hands = math.factorial(52)/(math.factorial(52-7)* math.factorial(7)) 


print(possible_completion*possible_anchor/possible_hands)

0.5956906237909666


In [901]:
from itertools import compress
list_a = ['a','b','temp',2]
fil = [True,True,False,True]
print(list(compress(list_a, fil)))


['a', 'b', 2]


In [936]:
list_a = [1, 2, 4, 6]
filter_vec = [True, False, True, False]
#iltered_list = [i for indx,i in enumerate(list_a) if filter_vec[indx]]
filtered_list = [ oddly for indx,oddly in enumerate(list_a) if filter_vec[indx]]
print(filtered_list)

        
        


[1, 4]


In [894]:
a =np.mgrid[0:5,0:5]
print(a.shape)
print(a)
b = np.zeros([2,3])
print(b[0,0])

x = np.array([1,2,3])
a = np.arange(3,dtype=int)
print(type(a))
a = np.reshape(a,(1,3))
a = np.repeat(a,3,axis=0)
#print(a * x)
#print(x.shape)
print(a.shape)

print(a[:,[0,1]])

(2, 5, 5)
[[[0 0 0 0 0]
  [1 1 1 1 1]
  [2 2 2 2 2]
  [3 3 3 3 3]
  [4 4 4 4 4]]

 [[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]]
0.0
<class 'numpy.ndarray'>
(3, 3)
[[0 1]
 [0 1]
 [0 1]]


In [ ]:
### determine if either player has any pairs
pairs_found = np.zeros(number_of_players,dtype=bool)
for player_index in range(number_of_players):
    unique_values, card_index = np.unique(hands[player_index,:,1],return_index=True)
    if len(unique_values)!=hands.shape[2]:
        pairs_found[player_index] = True
    Z

In [154]:
(5**3)/math.factorial(3)

20.833333333333332

In [156]:
(5*5*4)-(5*4*3)

40

In [157]:
(3*3*2) - (3*2*1)

12